### ISSUE TITLE
SSL support.

### ISSUE THREAD

**Issue by stephenkeep** [willrstern/tutum-nginx-load-balancing#1]
Is wildcard SSL supported?

**Comment by willrstern** [comment]
SSL support is definitely the next thing to be tackled.  

I'm thinking:
- add an `ssl` volume to an LB container with the certs
- certs are foldered by hostname
- include `{ssl: true}` in the server env variable
- do a generic SSL config - something like https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination

If people need a more specific SSL config, they can fork the repo.

**Comment by stephenkeep** [comment]
Thanks will and thank you for open sourcing it. I will be working on this today so will send a pull request.

**Comment by stephenkeep** [comment]
Thanks will and thank you for open sourcing it. If I get a chance to work on it today I'll send a pull request.

**Comment by willrstern** [comment]
covered it in https://github.com/willrstern/tutum-nginx-load-balancing/pull/2
